# Generated by Django 4.0.4 on 2022-07-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
