# Generated by Django 4.0.4 on 2022-07-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=1000)),
                ('paid', models.BooleanField(default=False)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
